// Generated by scripts/find-partners.mjs on 2026-10-02 from the public ARBK register (arbk.org).
window.VND_PARTNERS = [
 {
  "id": "812384428",
  "name": "Angolo Bar L.L.C.",
  "legal": "",
  "type": "food",
  "address": "UÇK, 10, Viti",
  "phone": "+38349722900",
  "email": "angoloklodian@gmail.com",
  "employees": 8,
  "founded": "2026-02-23",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/angolo-bar-llc/"
 },
 {
  "id": "812329648",
  "name": "Nexus Experiences SH.P.K.",
  "legal": "",
  "type": "food",
  "address": "MARTIRËT E KABASHIT, 61, Kabash",
  "phone": "+38344494849",
  "email": "nexusexperiences2026@gmail.com",
  "employees": 7,
  "founded": "2025-09-16",
  "naics": [
   "5610",
   "5630",
   "5920",
   "6010"
  ],
  "source": "https://arbk.org/biz/nexus-experiences-shpk/"
 },
 {
  "id": "812037613",
  "name": "PROPER PIZZA GD SH.P.K.",
  "legal": "",
  "type": "food",
  "address": "Rruga e UÇK-së , Nr.18, Viti",
  "phone": "+38348222314",
  "email": "vitiproperpizza@gmail.com",
  "employees": 7,
  "founded": "2023-04-28",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/proper-pizza-gd-shpk/"
 },
 {
  "id": "811096652",
  "name": "D.P.H. \" Jeta \"",
  "legal": "Xhevat Terziu B.I.",
  "type": "food",
  "address": "p.n., Pozheran",
  "phone": "+383280385825",
  "email": "",
  "employees": 6,
  "founded": "2010-10-01",
  "naics": [
   "5610"
  ],
  "source": "https://arbk.org/biz/xhevat-terziu-bi/"
 },
 {
  "id": "812044030",
  "name": "N&#8217;Perlë Lounge Bar SH.P.K.",
  "legal": "N’Perlë Lounge Bar SH.P.K.",
  "type": "food",
  "address": "Rr. Adem Jashari, p.n., Viti",
  "phone": "+38348588555",
  "email": "nperlshpk@gmail.com",
  "employees": 6,
  "founded": "2023-05-22",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/nperle-lounge-bar-shpk/"
 },
 {
  "id": "812042919",
  "name": "ANGOLO Restaurant",
  "legal": "VAAR SH.P.K.",
  "type": "food",
  "address": "UÇK, p.n, Viti",
  "phone": "+38344722228",
  "email": "vaar.shpk@gmail.com",
  "employees": 5,
  "founded": "2023-05-17",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/vaar-shpk/"
 },
 {
  "id": "811337717",
  "name": "D.P.H. \" Driloni \"",
  "legal": "Elsadat Halabaku B.I.",
  "type": "food",
  "address": "Rruga Izet Alidema, Pn, Pozharan",
  "phone": "+38349199580",
  "email": "elsadathalabaku@gmail.com",
  "employees": 5,
  "founded": "2007-09-25",
  "naics": [
   "5610",
   "5621",
   "5630"
  ],
  "source": "https://arbk.org/biz/elsadat-halabaku-bi/"
 },
 {
  "id": "811328758",
  "name": "Venecija",
  "legal": "Venecija SH.P.K.",
  "type": "food",
  "address": "Hoxhë Jonuzi, p.n., Viti",
  "phone": "+38344190114",
  "email": "bujar.sab@outlook.com",
  "employees": 5,
  "founded": "2019-07-08",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/venecija-shpk/"
 },
 {
  "id": "810031857",
  "name": "Genc Musa B.I.",
  "legal": "",
  "type": "food",
  "address": "Joseph R. Biden p.n., Pozheran",
  "phone": "+38345350052",
  "email": "",
  "employees": 4,
  "founded": "2017-06-07",
  "naics": [
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/genc-musa-bi/"
 },
 {
  "id": "810677148",
  "name": "Restoran Pizeria ,,Lindi-T\"",
  "legal": "Sinan Selimi B.I.",
  "type": "food",
  "address": "Adem Jashari, Viti",
  "phone": "+38344302824",
  "email": "",
  "employees": 4,
  "founded": "2003-04-17",
  "naics": [
   "5610"
  ],
  "source": "https://arbk.org/biz/sinan-selimi-bi/"
 },
 {
  "id": "810673526",
  "name": "D.P.H. \"METI \"",
  "legal": "Sejdi H. Krasniqi B.I.",
  "type": "food",
  "address": "Preshevës p.n., Viti",
  "phone": "+38344631817",
  "email": "",
  "employees": 3,
  "founded": "2000-09-04",
  "naics": [
   "5621",
   "5629"
  ],
  "source": "https://arbk.org/biz/sejdi-h-krasniqi-bi/"
 },
 {
  "id": "811523184",
  "name": "D.P.H. RESTAURANT \" YJET \"",
  "legal": "Avdi Ramushi B.I.",
  "type": "food",
  "address": "p.n., Kllokot",
  "phone": "+38345599066",
  "email": "",
  "employees": 3,
  "founded": "2012-12-07",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/avdi-ramushi-bi/"
 },
 {
  "id": "812019083",
  "name": "Fresh Pizza Viti",
  "legal": "Adnan R. Rushiti B.I.",
  "type": "food",
  "address": "Rruga Hoxhë Jonuzi, p.n., Viti",
  "phone": "+38349704347",
  "email": "akili5083@gmail.com",
  "employees": 3,
  "founded": "2023-03-01",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/adnan-r-rushiti-bi/"
 },
 {
  "id": "810069923",
  "name": "N.T.SH. \"Gryka e Moravës \"",
  "legal": "Ilire Zeneli B.I.",
  "type": "food",
  "address": "Shusht, Viti",
  "phone": "+38344635419",
  "email": "ilirezeneli@hotmail.com",
  "employees": 3,
  "founded": "2017-11-07",
  "naics": [
   "5610",
   "9319",
   "9329"
  ],
  "source": "https://arbk.org/biz/ilire-zeneli-bi/"
 },
 {
  "id": "811511999",
  "name": "Restaurant pizzeri D&D",
  "legal": "Restaurant pizzeri D&D SH.P.K.",
  "type": "food",
  "address": "Rruga Muhamet Muharremi, 0, Viti",
  "phone": "+38345953083",
  "email": "f.avdiu07@gmail.com",
  "employees": 3,
  "founded": "2021-02-26",
  "naics": [
   "5610",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/restaurant-pizzeri-dd-shpk/"
 },
 {
  "id": "811587031",
  "name": "Restaurant Pizzeri D&D GROUP",
  "legal": "Restaurant Pizzeri D&D GROUP SH.P.K.",
  "type": "food",
  "address": "Rr. E Presheves, p.n., Viti",
  "phone": "+38344292433",
  "email": "musaavdiu1961@gmail.com",
  "employees": 3,
  "founded": "2021-07-05",
  "naics": [
   "5610",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/restaurant-pizzeri-dd-group-shpk/"
 },
 {
  "id": "811468893",
  "name": "AMICI SH.P.K.",
  "legal": "",
  "type": "food",
  "address": "Rruga Adem Jashari, p.n, Viti",
  "phone": "+38344730287",
  "email": "amicishpk@gmail.com",
  "employees": 2,
  "founded": "2020-10-21",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/amici-shpk/"
 },
 {
  "id": "810170184",
  "name": "Arbnor Emini B.I.",
  "legal": "",
  "type": "food",
  "address": "Kllokot , Bajes p.n., Viti",
  "phone": "+38345901045",
  "email": "",
  "employees": 2,
  "founded": "2018-11-01",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/arbnor-emini-bi/"
 },
 {
  "id": "811586546",
  "name": "ARTA'OLTI",
  "legal": "ARTA’OLTI SH.P.K.",
  "type": "food",
  "address": "Rruga Budrika, nr 33, Budrikë e Epërme",
  "phone": "+38345578090",
  "email": "sylejmanialban44@gmail.com",
  "employees": 2,
  "founded": "2021-07-02",
  "naics": [
   "5610",
   "5621",
   "5630"
  ],
  "source": "https://arbk.org/biz/artaolti-shpk/"
 },
 {
  "id": "812391788",
  "name": "D.P.H. \" Te Lisi \"",
  "legal": "TE LISI MLI SH.P.K.",
  "type": "food",
  "address": "REXHEP BISLIMI, 69, Viti",
  "phone": "+38344396963",
  "email": "avdiuisak@gmail.com",
  "employees": 2,
  "founded": "2026-03-10",
  "naics": [
   "5621"
  ],
  "source": "https://arbk.org/biz/te-lisi-mli-shpk/"
 },
 {
  "id": "811398363",
  "name": "Dejan Rakić I.B.",
  "legal": "",
  "type": "food",
  "address": "Gazimestanka, p.n., Vërboc",
  "phone": "+38349748367",
  "email": "dekimiki16@hotmail.com",
  "employees": 2,
  "founded": "2020-02-10",
  "naics": [
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/dejan-rakic-ib/"
 },
 {
  "id": "811415919",
  "name": "EMPIRE INVEST",
  "legal": "EMPIRE INVEST L.L.C.",
  "type": "food",
  "address": "Rr.Bafti Haxhiu, p.n., Viti",
  "phone": "+38345987111",
  "email": "empireinvestllc20@gmail.com",
  "employees": 2,
  "founded": "2020-04-30",
  "naics": [
   "5610",
   "5630",
   "6810",
   "6831"
  ],
  "source": "https://arbk.org/biz/empire-invest-llc/"
 },
 {
  "id": "811969768",
  "name": "Emporium Lounge Bar Resto",
  "legal": "Emporium Lounge Bar Resto SH.P.K.",
  "type": "food",
  "address": "Rruga Hoxhë Jonuzi, p.n, Viti",
  "phone": "+38349708982",
  "email": "emporiumbarshpk@gmail.com",
  "employees": 2,
  "founded": "2022-09-19",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/emporium-lounge-bar-resto-shpk/"
 },
 {
  "id": "812009729",
  "name": "Fast Food D&A",
  "legal": "Fast Food D&A SH.P.K.",
  "type": "food",
  "address": "Magjistralja Ferizaj - Gjilan, p.n., Pozharan",
  "phone": "+38343839519",
  "email": "diamant.sallahu@gmail.com",
  "employees": 2,
  "founded": "2023-02-03",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/fast-food-da-shpk/"
 },
 {
  "id": "812369488",
  "name": "Food Cafe deni",
  "legal": "Sherif Saqipi B.I.",
  "type": "food",
  "address": "ADEM JASHARI, 45, Viti",
  "phone": "+38344376948",
  "email": "sherifsaqipi80@gmail.com",
  "employees": 2,
  "founded": "2026-01-21",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/sherif-saqipi-bi/"
 },
 {
  "id": "811975781",
  "name": "KASTRI GRILL",
  "legal": "KASTRI GRILL SH.P.K.",
  "type": "food",
  "address": "Rr. Brigada 173, p.n., Viti",
  "phone": "+38349673643",
  "email": "kastrigrillshpk@gmail.com",
  "employees": 2,
  "founded": "2022-10-11",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/kastri-grill-shpk/"
 },
 {
  "id": "812112134",
  "name": "Kastri Grill 2000",
  "legal": "Kastri Grill 2000 SH.P.K.",
  "type": "food",
  "address": "Rruga Brigada 173, P.N, Viti",
  "phone": "+38343513894",
  "email": "qendresakamberi21@icloud.com",
  "employees": 2,
  "founded": "",
  "naics": [
   "5610",
   "5621",
   "5629"
  ],
  "source": "https://arbk.org/biz/kastri-grill-2000-shpk/"
 },
 {
  "id": "812294255",
  "name": "KONAGI SH.P.K.",
  "legal": "",
  "type": "food",
  "address": "Adem Jashari, 72, Viti",
  "phone": "+38348870007",
  "email": "krenar_ismajli@hotmail.com",
  "employees": 2,
  "founded": "2025-06-16",
  "naics": [
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/konagi-shpk/"
 },
 {
  "id": "811103142",
  "name": "N.SH. \" YLLI \"",
  "legal": "Drita Musliu B.I.",
  "type": "food",
  "address": "Preshevës p.n., Viti",
  "phone": "+38344250651",
  "email": "",
  "employees": 2,
  "founded": "2014-08-11",
  "naics": [
   "5610"
  ],
  "source": "https://arbk.org/biz/drita-musliu-bi/"
 },
 {
  "id": "812162121",
  "name": "Pastrimi Plus",
  "legal": "Pastrimi Plus SH.P.K.",
  "type": "food",
  "address": "Rr: Hamit Ymeri , P.N, Sllatinë e Epërme",
  "phone": "+38344704595",
  "email": "pastrimi-pluss@hotmail.com",
  "employees": 2,
  "founded": "2024-05-20",
  "naics": [
   "5610",
   "5630",
   "8121",
   "8122"
  ],
  "source": "https://arbk.org/biz/pastrimi-plus-shpk/"
 },
 {
  "id": "810001446",
  "name": "Restaurant DRURI SH.P.K.",
  "legal": "",
  "type": "food",
  "address": "Ramjani p.n., Novosellë",
  "phone": "+38344225553",
  "email": "",
  "employees": 2,
  "founded": "2017-03-01",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/restaurant-druri-shpk/"
 },
 {
  "id": "811572313",
  "name": "RESTAURANT FAMILY ÇOÇA HOME",
  "legal": "RESTAURANT FAMILY ÇOÇA HOME SH.P.K.",
  "type": "food",
  "address": "p.n, pn, Pozharan",
  "phone": "+38345437070",
  "email": "asabedini@hotmail.com",
  "employees": 2,
  "founded": "2021-05-21",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/restaurant-family-coca-home-shpk/"
 },
 {
  "id": "812370675",
  "name": "Restaurant Guri Kuq SH.P.K.",
  "legal": "",
  "type": "food",
  "address": "DUSHKU, 310, Sadovinë e Jerlive",
  "phone": "+38344719288",
  "email": "shkurte.deliu88@gmail.com",
  "employees": 2,
  "founded": "2026-01-23",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/restaurant-guri-kuq-shpk/"
 },
 {
  "id": "812094093",
  "name": "RESTAURANT PIZZERI INNTEX",
  "legal": "Xhelal S. Selimi B.I.",
  "type": "food",
  "address": "Rruga Izet Alidema, P.n., Pozharan",
  "phone": "+38345909332",
  "email": "xhelalselimi@icloud.com",
  "employees": 2,
  "founded": "2023-10-25",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/xhelal-s-selimi-bi/"
 },
 {
  "id": "812447812",
  "name": "Restaurant VALENTA SH.P.K.",
  "legal": "",
  "type": "food",
  "address": "RAMJANI, 160, Ramjan",
  "phone": "+38345653417",
  "email": "restaurantvalenta@hotmail.com",
  "employees": 2,
  "founded": "2026-07-29",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/restaurant-valenta-shpk/"
 },
 {
  "id": "811093038",
  "name": "Restorant Lindi SH.P.K.",
  "legal": "",
  "type": "food",
  "address": "Adem Jashari p.n., Viti",
  "phone": "+38344646048",
  "email": "",
  "employees": 2,
  "founded": "2016-02-26",
  "naics": [
   "5610"
  ],
  "source": "https://arbk.org/biz/restorant-lindi-shpk/"
 },
 {
  "id": "810044074",
  "name": "Te Aga Nez SH.P.K.",
  "legal": "",
  "type": "food",
  "address": "p.n., Ramnishtë",
  "phone": "+38344906659",
  "email": "",
  "employees": 2,
  "founded": "2017-07-25",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/te-aga-nez-shpk/"
 },
 {
  "id": "811592197",
  "name": "Te Nana",
  "legal": "Ibadete Jahiri B.I.",
  "type": "food",
  "address": "Rruga Dushku, 122, Sadovinë e Jerlive",
  "phone": "+38345457735",
  "email": "ajaltrans@gmail.com",
  "employees": 2,
  "founded": "2021-07-16",
  "naics": [
   "5610"
  ],
  "source": "https://arbk.org/biz/ibadete-jahiri-bi/"
 },
 {
  "id": "812054295",
  "name": "Te Vali Caffe",
  "legal": "Te Vali Caffe SH.P.K.",
  "type": "food",
  "address": "Rruga Shaban Haliti, 5, Pozharan",
  "phone": "+38345804013",
  "email": "zukameriton@gmail.com",
  "employees": 2,
  "founded": "2023-06-20",
  "naics": [
   "5629",
   "5630",
   "9602",
   "9609"
  ],
  "source": "https://arbk.org/biz/te-vali-caffe-shpk/"
 },
 {
  "id": "810165432",
  "name": "TRADITA BURON SH.P.K.",
  "legal": "",
  "type": "food",
  "address": "Tiranës p.n., Viti",
  "phone": "+38345900692",
  "email": "",
  "employees": 2,
  "founded": "2018-10-15",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/tradita-buron-shpk/"
 },
 {
  "id": "811095604",
  "name": "U.P. \" Dubrovnik \"",
  "legal": "Milorad Šotic B.I.",
  "type": "food",
  "address": "b.b., Letnicë",
  "phone": "+38349707694",
  "email": "",
  "employees": 2,
  "founded": "2010-01-11",
  "naics": [
   "5610",
   "5621",
   "5630"
  ],
  "source": "https://arbk.org/biz/milorad-sotic-bi/"
 },
 {
  "id": "811316852",
  "name": "8A8",
  "legal": "8A8 SH.P.K.",
  "type": "food",
  "address": "Rruga Adem Jashari, p.n., Viti",
  "phone": "+38349666994",
  "email": "kushtrimxhemajli9@gmail.com",
  "employees": 1,
  "founded": "2019-06-06",
  "naics": [
   "5610",
   "5629",
   "5630",
   "9329"
  ],
  "source": "https://arbk.org/biz/8a8-shpk/"
 },
 {
  "id": "812369876",
  "name": "Ahmet S. Krasniqi B.I.",
  "legal": "",
  "type": "food",
  "address": "REXHEP BISLIMI, 53, Viti",
  "phone": "+38344596703",
  "email": "ahmet.krasniqi21@icloud.com",
  "employees": 1,
  "founded": "2026-01-22",
  "naics": [
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/ahmet-s-krasniqi-bi/"
 },
 {
  "id": "810146713",
  "name": "Arlind Alidema B.I.",
  "legal": "",
  "type": "food",
  "address": "p.n., Pozheran",
  "phone": "+38345529255",
  "email": "",
  "employees": 1,
  "founded": "2018-08-07",
  "naics": [
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/arlind-alidema-bi/"
 },
 {
  "id": "810157348",
  "name": "BIG BEN CAFFE BAR SH.P.K.",
  "legal": "",
  "type": "food",
  "address": "Adem Jashari p.n., Viti",
  "phone": "+38344370391",
  "email": "",
  "employees": 1,
  "founded": "2018-09-19",
  "naics": [
   "5610",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/big-ben-caffe-bar-shpk/"
 },
 {
  "id": "810088189",
  "name": "BJONDINA MAKEUP HAIR",
  "legal": "Muzafere Rexhepi B.I.",
  "type": "food",
  "address": "Rruga Florim Maliqi, 122, Viti",
  "phone": "+38344461628",
  "email": "muzafererexhepi@tmail.com",
  "employees": 1,
  "founded": "2018-01-25",
  "naics": [
   "5629",
   "5630",
   "9602"
  ],
  "source": "https://arbk.org/biz/muzafere-rexhepi-bi/"
 },
 {
  "id": "810028440",
  "name": "Bujar I. Avdyli B.I.",
  "legal": "",
  "type": "food",
  "address": "Adem Jashari p.n., Viti",
  "phone": "+38344324457",
  "email": "",
  "employees": 1,
  "founded": "2017-05-24",
  "naics": [
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/bujar-i-avdyli-bi/"
 },
 {
  "id": "810012930",
  "name": "Bukurije Rexhepi B.I.",
  "legal": "",
  "type": "food",
  "address": "Iliria p.n., Viti",
  "phone": "+38344322609",
  "email": "",
  "employees": 1,
  "founded": "2017-04-03",
  "naics": [
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/bukurije-rexhepi-bi/"
 },
 {
  "id": "811390187",
  "name": "Caffe Bar Street 06",
  "legal": "Caffe Bar Street 06 SH.P.K.",
  "type": "food",
  "address": "Hoxhë Jonuzi, p.n., Viti",
  "phone": "+38344250284",
  "email": "gezimaliu2020@gmail.com",
  "employees": 1,
  "founded": "2020-01-20",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/caffe-bar-street-06-shpk/"
 },
 {
  "id": "811299842",
  "name": "Caffeteria Friends Avenue Quni",
  "legal": "Caffeteria Friends Avenue Quni SH.P.K.",
  "type": "food",
  "address": "Hoxhë Jonuzi, p.n., Viti",
  "phone": "+38344341778",
  "email": "avenuequni@gmail.com",
  "employees": 1,
  "founded": "2019-04-25",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/caffeteria-friends-avenue-quni-shpk/"
 },
 {
  "id": "811862590",
  "name": "Cafiteria Roni",
  "legal": "Agron A. Sahiti B.I.",
  "type": "food",
  "address": "Rruga Dëshmorët e Kombit, p.n., Budrikë e Epërme",
  "phone": "+38345894205",
  "email": "agronsahiti@hotmail.com",
  "employees": 1,
  "founded": "2021-09-22",
  "naics": [
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/agron-a-sahiti-bi/"
 },
 {
  "id": "811096975",
  "name": "D.P.H. \" JETA - 1 \"",
  "legal": "Qerim N. Krasniqi B.I.",
  "type": "food",
  "address": "Dëshmorët e Vitisë, Viti",
  "phone": "+38344647566",
  "email": "",
  "employees": 1,
  "founded": "2011-02-01",
  "naics": [
   "5621",
   "5629"
  ],
  "source": "https://arbk.org/biz/qerim-n-krasniqi-bi/"
 },
 {
  "id": "811094276",
  "name": "D.P.H. \" Kastri \"",
  "legal": "Kastriot Ahmeti B.I.",
  "type": "food",
  "address": "Adem Jashari, Viti",
  "phone": "+38344466364",
  "email": "",
  "employees": 1,
  "founded": "2008-10-07",
  "naics": [
   "5621",
   "5629"
  ],
  "source": "https://arbk.org/biz/kastriot-ahmeti-bi/"
 },
 {
  "id": "811102368",
  "name": "D.P.H. \" LABI - R \"",
  "legal": "Labinot S. Ramadani B.I.",
  "type": "food",
  "address": "p.n., Budrikë e Epërme",
  "phone": "+38344753752",
  "email": "",
  "employees": 1,
  "founded": "2014-02-06",
  "naics": [
   "5610",
   "5630"
  ],
  "source": "https://arbk.org/biz/labinot-s-ramadani-bi/"
 },
 {
  "id": "811095563",
  "name": "D.P.H. \" SHQIPONJA \"",
  "legal": "Hekrush Haliti B.I.",
  "type": "food",
  "address": "2 Korriku, Viti",
  "phone": "+38344376671",
  "email": "",
  "employees": 1,
  "founded": "2009-12-17",
  "naics": [
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/hekrush-haliti-bi/"
 },
 {
  "id": "811310268",
  "name": "D.P.H. \" TE BACI \"",
  "legal": "Milaim F. Rexhepi B.I.",
  "type": "food",
  "address": "Pozheran",
  "phone": "+38344480924",
  "email": "",
  "employees": 1,
  "founded": "2010-06-30",
  "naics": [
   "5621",
   "5629"
  ],
  "source": "https://arbk.org/biz/milaim-f-rexhepi-bi/"
 },
 {
  "id": "810672990",
  "name": "D.P.H. \" Zabeli \"",
  "legal": "Danush Misini B.I.",
  "type": "food",
  "address": "Tirana, Viti",
  "phone": "+38344193702",
  "email": "",
  "employees": 1,
  "founded": "2000-08-24",
  "naics": [
   "5621",
   "5629"
  ],
  "source": "https://arbk.org/biz/danush-misini-bi/"
 },
 {
  "id": "811094383",
  "name": "D.P.H. \"Kushtrimi\"",
  "legal": "Fadil Zuka B.I.",
  "type": "food",
  "address": "Rruga Haxhi Emini, p.n., Pozharan",
  "phone": "+38344250002",
  "email": "kushtrimzuka0@gmail.com",
  "employees": 1,
  "founded": "2008-11-13",
  "naics": [
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/fadil-zuka-bi/"
 },
 {
  "id": "811101550",
  "name": "D.P.H. Qebaptore \" SHEKI \"",
  "legal": "Shefk Marku B.I.",
  "type": "food",
  "address": "Brigada 173 p.n., Viti",
  "phone": "+38344461283",
  "email": "",
  "employees": 1,
  "founded": "2013-07-26",
  "naics": [
   "5621"
  ],
  "source": "https://arbk.org/biz/shefk-marku-bi/"
 },
 {
  "id": "811274000",
  "name": "Danijel Kojić I.B.",
  "legal": "",
  "type": "food",
  "address": "verboc, p.n, Vërboc",
  "phone": "+38349599189",
  "email": "danijelkojiq@hotmail.com",
  "employees": 1,
  "founded": "2019-02-26",
  "naics": [
   "5629",
   "5630",
   "9329"
  ],
  "source": "https://arbk.org/biz/danijel-kojic-ib/"
 },
 {
  "id": "811914466",
  "name": "Döner LIKI",
  "legal": "Fatmir Hamiti B.I.",
  "type": "food",
  "address": "Rruga Hoxhë Jonuzi, pn, Viti",
  "phone": "+38349816821",
  "email": "fhamiti55@gmail.com",
  "employees": 1,
  "founded": "2022-03-22",
  "naics": [
   "5621",
   "5629"
  ],
  "source": "https://arbk.org/biz/fatmir-hamiti-bi/"
 },
 {
  "id": "810135154",
  "name": "Dorian Alidema B.I.",
  "legal": "",
  "type": "food",
  "address": "Magjistralja Ferizaj - Gjilan p.n., Pozheran",
  "phone": "+38344559837",
  "email": "",
  "employees": 1,
  "founded": "2018-06-25",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/dorian-alidema-bi/"
 },
 {
  "id": "812093334",
  "name": "DYNER FLAKRIMI",
  "legal": "DYNER FLAKRIMI SH.P.K.",
  "type": "food",
  "address": "Rruga Gjemail Ademi, P.n., Viti",
  "phone": "+38344863685",
  "email": "flakrimmaliqi756@gmail.com",
  "employees": 1,
  "founded": "2023-10-23",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/dyner-flakrimi-shpk/"
 },
 {
  "id": "811578262",
  "name": "Erta AA",
  "legal": "Erta AA SH.P.K.",
  "type": "food",
  "address": "Rruga Dëshmorët e Kombit, pn, Viti",
  "phone": "+38344159136",
  "email": "ertashpk@hotmail.com",
  "employees": 1,
  "founded": "2021-06-07",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/erta-aa-shpk/"
 },
 {
  "id": "812385955",
  "name": "Fast Food Mrizi SH.P.K.",
  "legal": "",
  "type": "food",
  "address": "ADEM JASHARI, 60, Viti",
  "phone": "+38345805151",
  "email": "rina.rexhepi2005@outlook.com",
  "employees": 1,
  "founded": "2026-02-26",
  "naics": [
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/fast-food-mrizi-shpk/"
 },
 {
  "id": "811099721",
  "name": "Faton Kurteshi B.I.",
  "legal": "",
  "type": "food",
  "address": "Rr. Dëshmoret e Vitisë p.n., Viti",
  "phone": "+38344710689",
  "email": "",
  "employees": 1,
  "founded": "2012-10-23",
  "naics": [
   "5610",
   "5630",
   "9001",
   "9002"
  ],
  "source": "https://arbk.org/biz/faton-kurteshi-bi/"
 },
 {
  "id": "810125923",
  "name": "Fitim V. Hasani B.I.",
  "legal": "",
  "type": "food",
  "address": "Adem Jashari p.n., Viti",
  "phone": "+38349999461",
  "email": "",
  "employees": 1,
  "founded": "2018-05-22",
  "naics": [
   "5610",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/fitim-v-hasani-bi/"
 },
 {
  "id": "811853820",
  "name": "FLUSS",
  "legal": "Hekuran Tafa B.I.",
  "type": "food",
  "address": "Rruga Agim Ramadani, nr.48, Viti",
  "phone": "+38349843681",
  "email": "hekurantafa@gmail.c",
  "employees": 1,
  "founded": "2021-08-20",
  "naics": [
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/hekuran-tafa-bi/"
 },
 {
  "id": "812317411",
  "name": "French Tacos & pizza",
  "legal": "Arjeton Haliti B.I.",
  "type": "food",
  "address": "UÇK, 102, Viti",
  "phone": "+38345344364",
  "email": "arjeton.haliti1996@gmail.com",
  "employees": 1,
  "founded": "2025-08-12",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/arjeton-haliti-bi/"
 },
 {
  "id": "812235952",
  "name": "Gjelltore Piceri ELI SH.P.K.",
  "legal": "",
  "type": "food",
  "address": "Rruga \"Brigada 173\", Nr.146, Viti",
  "phone": "+38345368488",
  "email": "lumazemi140@gmail.com",
  "employees": 1,
  "founded": "2025-01-10",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/gjelltore-piceri-eli-shpk/"
 },
 {
  "id": "810031378",
  "name": "Granit S. Emini B.I.",
  "legal": "",
  "type": "food",
  "address": "Rruga Brigada 173, p.n., Viti",
  "phone": "+38349730880",
  "email": "granit_0@hotmail.com",
  "employees": 1,
  "founded": "2017-06-06",
  "naics": [
   "5621",
   "5629",
   "5630",
   "7711"
  ],
  "source": "https://arbk.org/biz/granit-s-emini-bi/"
 },
 {
  "id": "811585530",
  "name": "Guri i Bardhë",
  "legal": "Guri i Bardhë SH.P.K.",
  "type": "food",
  "address": "Ilaz Debelldehu, p.n., Debelldeh",
  "phone": "+38348675660",
  "email": "besartarama@hotmail.com",
  "employees": 1,
  "founded": "2021-06-30",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/guri-i-bardhe-shpk/"
 },
 {
  "id": "811468752",
  "name": "HALLALL PIZZA DARDANI",
  "legal": "Dardan Nuredini B.I.",
  "type": "food",
  "address": "Preshevës, p.n., Viti",
  "phone": "+38344564996",
  "email": "dardannuredini@outlook.com",
  "employees": 1,
  "founded": "2020-10-20",
  "naics": [
   "5610",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/dardan-nuredini-bi/"
 },
 {
  "id": "811499012",
  "name": "HAWAII BAR",
  "legal": "HAWAII BAR SH.P.K.",
  "type": "food",
  "address": "Rruga Adem Jashari, p.n., Viti",
  "phone": "+38344194218",
  "email": "hawaiibarshpk@outlook.com",
  "employees": 1,
  "founded": "2021-01-21",
  "naics": [
   "5610",
   "5630"
  ],
  "source": "https://arbk.org/biz/hawaii-bar-shpk/"
 },
 {
  "id": "811951442",
  "name": "Kafiteria Misini",
  "legal": "Egxona Quni B.I.",
  "type": "food",
  "address": "Rruga Arbëria, p.n., Gërmovë",
  "phone": "+38349489410",
  "email": "avdimisini@autlook.com",
  "employees": 1,
  "founded": "2022-07-15",
  "naics": [
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/egxona-quni-bi/"
 },
 {
  "id": "811549437",
  "name": "Kafja Irina",
  "legal": "Arjan Kuka B.I.",
  "type": "food",
  "address": "Mejdi Korani, p.n, Pozharan",
  "phone": "+38344989523",
  "email": "ariankuka88@gmail.com",
  "employees": 1,
  "founded": "2021-03-09",
  "naics": [
   "5610",
   "5621",
   "5630",
   "5920"
  ],
  "source": "https://arbk.org/biz/arjan-kuka-bi/"
 },
 {
  "id": "810012857",
  "name": "Kastriot N. Sylejmani B.I.",
  "legal": "",
  "type": "food",
  "address": "Adem Jashari p.n., Viti",
  "phone": "+38344406574",
  "email": "",
  "employees": 1,
  "founded": "2017-04-03",
  "naics": [
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/kastriot-n-sylejmani-bi/"
 },
 {
  "id": "812246925",
  "name": "KikiGrill SH.P.K.",
  "legal": "",
  "type": "food",
  "address": "Rexhep Bislimi , p.n., Viti",
  "phone": "+38344555289",
  "email": "infokikigrill@gmail.com",
  "employees": 1,
  "founded": "2025-02-10",
  "naics": [
   "5610",
   "5621"
  ],
  "source": "https://arbk.org/biz/kikigrill-shpk/"
 },
 {
  "id": "811981142",
  "name": "KOHA B",
  "legal": "KOHA B SH.P.K.",
  "type": "food",
  "address": "Magjistralja gjilan - Ferizaj, p.n., Pozharan",
  "phone": "+38349133391",
  "email": "halimib060@gmail.com",
  "employees": 1,
  "founded": "2022-10-31",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/koha-b-shpk/"
 },
 {
  "id": "812308957",
  "name": "Kushtrim D. Misini B.I.",
  "legal": "",
  "type": "food",
  "address": "Rr: 2 Korriku, PN., Viti",
  "phone": "+38344666205",
  "email": "liridonzejnullahu@hotmail.com",
  "employees": 1,
  "founded": "2025-07-21",
  "naics": [
   "5621",
   "5629"
  ],
  "source": "https://arbk.org/biz/kushtrim-d-misini-bi/"
 },
 {
  "id": "811105213",
  "name": "Miloš Kojić I.B.",
  "legal": "Miloš Kojic I.B.",
  "type": "food",
  "address": "p.n., Vrbofc",
  "phone": "+38349623405",
  "email": "",
  "employees": 1,
  "founded": "2016-02-26",
  "naics": [
   "5629",
   "5630",
   "9329"
  ],
  "source": "https://arbk.org/biz/milos-kojic-ib/"
 },
 {
  "id": "812317362",
  "name": "MJ TONY",
  "legal": "Jeton B. Misini B.I.",
  "type": "food",
  "address": "DITURIA, 26, Gërmovë",
  "phone": "+38344470004",
  "email": "misini_1205@hotmail.fr",
  "employees": 1,
  "founded": "2025-08-12",
  "naics": [
   "5610"
  ],
  "source": "https://arbk.org/biz/jeton-b-misini-bi/"
 },
 {
  "id": "811935066",
  "name": "MOROKO",
  "legal": "Albanor Imeri B.I.",
  "type": "food",
  "address": "Rr. Mirali Sejdiu, p.n., Smirë",
  "phone": "+38344743115",
  "email": "nolyy12@gmail.com",
  "employees": 1,
  "founded": "2022-05-26",
  "naics": [
   "5610",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/albanor-imeri-bi/"
 },
 {
  "id": "810672362",
  "name": "P.P.Z. \" RINIA \"",
  "legal": "Refik Haliti B.I.",
  "type": "food",
  "address": "Brigada 173, Viti",
  "phone": "+38344341782",
  "email": "",
  "employees": 1,
  "founded": "2002-04-02",
  "naics": [
   "5621",
   "5629"
  ],
  "source": "https://arbk.org/biz/refik-haliti-bi/"
 },
 {
  "id": "810673534",
  "name": "P.P.Z.,,Bashkimi\"",
  "legal": "Bashkim J. Haziri B.I.",
  "type": "food",
  "address": "UÇK, 54, Viti",
  "phone": "+38344210765",
  "email": "bashkimhazizi2020@outlook.com",
  "employees": 1,
  "founded": "2000-09-04",
  "naics": [
   "5621",
   "5629"
  ],
  "source": "https://arbk.org/biz/bashkim-j-haziri-bi/"
 },
 {
  "id": "811382887",
  "name": "Res Loli",
  "legal": "Burim Xheladini B.I.",
  "type": "food",
  "address": "Arif Arifi, p.n., Smirë",
  "phone": "+38349706806",
  "email": "burimxheladini@hotmail.com",
  "employees": 1,
  "founded": "2019-12-17",
  "naics": [
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/burim-xheladini-bi/"
 },
 {
  "id": "812125476",
  "name": "RESTAURANT BAR INNTEX",
  "legal": "Driton Selimi B.I.",
  "type": "food",
  "address": "Rruga Izet Alidema, p.n., Pozharan",
  "phone": "+38344749700",
  "email": "restaurant_inntex@outlook.com",
  "employees": 1,
  "founded": "2024-02-06",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/driton-selimi-bi/"
 },
 {
  "id": "810194100",
  "name": "Restaurant Roi SH.P.K.",
  "legal": "",
  "type": "food",
  "address": "Adem Jashari p.n., Viti",
  "phone": "+38349705996",
  "email": "",
  "employees": 1,
  "founded": "2019-01-31",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/restaurant-roi-shpk/"
 },
 {
  "id": "812024975",
  "name": "SUB FAST FOOD",
  "legal": "SUB FAST FOOD SH.P.K.",
  "type": "food",
  "address": "Rruga Flaka e Janarit, p.n., Viti",
  "phone": "+38344892849",
  "email": "kristjandokaj1991@gmail.com",
  "employees": 1,
  "founded": "2023-03-16",
  "naics": [
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/sub-fast-food-shpk/"
 },
 {
  "id": "811419888",
  "name": "Te Loriku",
  "legal": "Shqiponja Jahiri B.I.",
  "type": "food",
  "address": "Jasharët p.n., p.n., Vërban",
  "phone": "+38344579429",
  "email": "shqiponjajahiri@hotmail.com",
  "employees": 1,
  "founded": "2020-05-15",
  "naics": [
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/shqiponja-jahiri-bi/"
 },
 {
  "id": "811390799",
  "name": "Te Meti Faruk SH.P.K.",
  "legal": "",
  "type": "food",
  "address": "Rr. Hoxhë Jonuzi,, p.n, Viti",
  "phone": "+38344154239",
  "email": "dautihajrush@gmail.com",
  "employees": 1,
  "founded": "2020-01-21",
  "naics": [
   "5610",
   "5629"
  ],
  "source": "https://arbk.org/biz/te-meti-faruk-shpk/"
 },
 {
  "id": "812059956",
  "name": "Tempo Terasa",
  "legal": "Tempo Terasa SH.P.K.",
  "type": "food",
  "address": "Rruga Adem Jashari, /, Viti",
  "phone": "+38349684447",
  "email": "f.avdiu07@gmail.com",
  "employees": 1,
  "founded": "2023-07-10",
  "naics": [
   "5610",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/tempo-terasa-shpk/"
 },
 {
  "id": "812163153",
  "name": "The coffee house",
  "legal": "Mirlinda Zefi B.I.",
  "type": "food",
  "address": "Ibrahim Rugova, p.n., Drobesh",
  "phone": "+38349715389",
  "email": "lindazefii06@icloud.com",
  "employees": 1,
  "founded": "2024-05-23",
  "naics": [
   "5610",
   "5630"
  ],
  "source": "https://arbk.org/biz/mirlinda-zefi-bi/"
 },
 {
  "id": "812030261",
  "name": "TITI FAST FOOD",
  "legal": "TITI FAST FOOD SH.P.K.",
  "type": "food",
  "address": "Rruga Flaka e Janarit, p.n., Viti",
  "phone": "+38349520640",
  "email": "xhevahiri1122@gmail.com",
  "employees": 1,
  "founded": "2023-03-31",
  "naics": [
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/titi-fast-food-shpk/"
 },
 {
  "id": "812106038",
  "name": "UNO BAR SH.P.K.",
  "legal": "",
  "type": "food",
  "address": "Rr. Adem Jashari, p.n., Viti",
  "phone": "+38343815794",
  "email": "uno.bar.viti@gmail.com",
  "employees": 1,
  "founded": "2023-12-01",
  "naics": [
   "5610",
   "5630"
  ],
  "source": "https://arbk.org/biz/uno-bar-shpk/"
 },
 {
  "id": "811913202",
  "name": "VANILLA 1951",
  "legal": "VANILLA 1951 SH.P.K.",
  "type": "food",
  "address": "xhemajl Ademi, nr. 52, Viti",
  "phone": "+38348500054",
  "email": "harisibishi@gmail.com",
  "employees": 1,
  "founded": "2022-03-18",
  "naics": [
   "5610",
   "5621",
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/vanilla-1951-shpk/"
 },
 {
  "id": "811106287",
  "name": "Vebi Shaqiri B.I.",
  "legal": "",
  "type": "food",
  "address": "p.n., Pozheran",
  "phone": "+38344383828",
  "email": "",
  "employees": 1,
  "founded": "2017-02-27",
  "naics": [
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/vebi-shaqiri-bi/"
 },
 {
  "id": "810033754",
  "name": "Zeqir Il. Arifi B.I.",
  "legal": "",
  "type": "food",
  "address": "Preshevës p.n., Viti",
  "phone": "+38344995267",
  "email": "",
  "employees": 1,
  "founded": "2017-06-15",
  "naics": [
   "5629",
   "5630"
  ],
  "source": "https://arbk.org/biz/zeqir-il-arifi-bi/"
 },
 {
  "id": "810028002",
  "name": "Q.T. ELA – CENTER SH.P.K.",
  "legal": "",
  "type": "market",
  "address": "Viti-Gërlicë, Drobesh",
  "phone": "+38349425333",
  "email": "",
  "employees": 5,
  "founded": "2017-05-22",
  "naics": [
   "4711",
   "4719",
   "4721",
   "4722"
  ],
  "source": "https://arbk.org/biz/qt-ela-center-shpk/"
 },
 {
  "id": "812413532",
  "name": "Restorant MUSA",
  "legal": "MUSA MM MARKET SH.P.K.",
  "type": "market",
  "address": "2 KORRIKU, 8, Viti",
  "phone": "+38344690773",
  "email": "alushrexhepi1@gmail.com",
  "employees": 3,
  "founded": "2026-05-06",
  "naics": [
   "4711",
   "4719",
   "4721",
   "4722"
  ],
  "source": "https://arbk.org/biz/musa-mm-market-shpk/"
 },
 {
  "id": "810678849",
  "name": "`N.T.P. \" Real Center \"",
  "legal": "Bajram Ymeri B.I.",
  "type": "market",
  "address": "Tiranës, Viti",
  "phone": "+38344193865",
  "email": "",
  "employees": 2,
  "founded": "2006-06-07",
  "naics": [
   "4711",
   "4778"
  ],
  "source": "https://arbk.org/biz/bajram-ymeri-bi/"
 },
 {
  "id": "810022509",
  "name": "Baf Petrol SH.P.K.",
  "legal": "",
  "type": "market",
  "address": "Ramnishtë",
  "phone": "+38344431632",
  "email": "",
  "employees": 2,
  "founded": "2017-05-03",
  "naics": [
   "4711",
   "4730"
  ],
  "source": "https://arbk.org/biz/baf-petrol-shpk/"
 },
 {
  "id": "811501007",
  "name": "BAJRA COMM",
  "legal": "BAJRA COMM SH.P.K.",
  "type": "market",
  "address": "Rruga Vërbani, p.n., Vërban",
  "phone": "+38344528996",
  "email": "sokoli.bajram5@gmail.com",
  "employees": 2,
  "founded": "2021-01-27",
  "naics": [
   "4711",
   "4719",
   "4721",
   "4722"
  ],
  "source": "https://arbk.org/biz/bajra-comm-shpk/"
 },
 {
  "id": "811983974",
  "name": "BASHKIMI ALBI",
  "legal": "BASHKIMI ALBI SH.P.K.",
  "type": "market",
  "address": "Sllatinë e Epërme, pn, Sllatinë e Epërme",
  "phone": "+38344249967",
  "email": "marketbashkimi@gmail.com",
  "employees": 2,
  "founded": "2022-11-08",
  "naics": [
   "4711"
  ],
  "source": "https://arbk.org/biz/bashkimi-albi-shpk/"
 },
 {
  "id": "811873373",
  "name": "Missini",
  "legal": "Avdi N. Misini B.I.",
  "type": "market",
  "address": "Rruga Arbëria, p.n., Gërmovë",
  "phone": "+38349489410",
  "email": "avdimisini@outlook.com",
  "employees": 2,
  "founded": "2021-10-28",
  "naics": [
   "4711",
   "4721",
   "4724",
   "4725"
  ],
  "source": "https://arbk.org/biz/avdi-n-misini-bi/",
  "dupPhone": true
 },
 {
  "id": "811350652",
  "name": "N.T.SH. \" SYRI \"",
  "legal": "Taib Alidemi B.I.",
  "type": "market",
  "address": "Preshevës p.n., Viti",
  "phone": "+38344194252",
  "email": "",
  "employees": 2,
  "founded": "2015-02-06",
  "naics": [
   "4711",
   "4719",
   "4721",
   "4751"
  ],
  "source": "https://arbk.org/biz/taib-alidemi-bi/"
 },
 {
  "id": "810142381",
  "name": "OLTA SH.P.K.",
  "legal": "",
  "type": "market",
  "address": "Magjistralja Ferizaj - Gjilan p.n., Radivojcë",
  "phone": "+38344783432",
  "email": "",
  "employees": 2,
  "founded": "2018-07-20",
  "naics": [
   "4711",
   "4721",
   "4722",
   "4723"
  ],
  "source": "https://arbk.org/biz/olta-shpk/"
 },
 {
  "id": "812285858",
  "name": "Retro Tavern SH.P.K.",
  "legal": "",
  "type": "market",
  "address": "Magjistralja Ferizaj - Gjilan , nr. 160, Novosellë",
  "phone": "+38345474616",
  "email": "landrit.zuk@gmail.com",
  "employees": 2,
  "founded": "2025-05-26",
  "naics": [
   "4722",
   "5610",
   "5621",
   "5629"
  ],
  "source": "https://arbk.org/biz/retro-tavern-shpk/"
 },
 {
  "id": "811863019",
  "name": "Valdrin Pajaziti B.I.",
  "legal": "",
  "type": "market",
  "address": "Tiranës, p.n., Viti",
  "phone": "+38349764756",
  "email": "valdrinpajaziti7@gmail.com",
  "employees": 2,
  "founded": "2021-09-23",
  "naics": [
   "4711",
   "4721",
   "4724",
   "4725"
  ],
  "source": "https://arbk.org/biz/valdrin-pajaziti-bi/"
 },
 {
  "id": "811105320",
  "name": "Agron G. Hyseni B.I.",
  "legal": "",
  "type": "market",
  "address": "Gjemail Ademi p.n., Viti",
  "phone": "+38344444538",
  "email": "",
  "employees": 1,
  "founded": "2016-03-17",
  "naics": [
   "4711",
   "4729"
  ],
  "source": "https://arbk.org/biz/agron-g-hyseni-bi/"
 },
 {
  "id": "811105742",
  "name": "Arban Demelezi B.I.",
  "legal": "",
  "type": "market",
  "address": "Mehmet Demelezi p.n., Sllatinë e Poshtme",
  "phone": "+38344567950",
  "email": "",
  "employees": 1,
  "founded": "2016-08-18",
  "naics": [
   "4711",
   "4721",
   "4724",
   "4751"
  ],
  "source": "https://arbk.org/biz/arban-demelezi-bi/"
 },
 {
  "id": "811105049",
  "name": "Azem Haziri B.I.",
  "legal": "",
  "type": "market",
  "address": "2 Korriku p.n., Viti",
  "phone": "+38349714599",
  "email": "",
  "employees": 1,
  "founded": "2016-01-11",
  "naics": [
   "4721",
   "4725"
  ],
  "source": "https://arbk.org/biz/azem-haziri-bi/"
 },
 {
  "id": "811333707",
  "name": "Besarta Misini B.I.",
  "legal": "",
  "type": "market",
  "address": "Misini, p.n., Sadovinë e Jerlive",
  "phone": "+38344555316",
  "email": "misinibesarta@gmail.com",
  "employees": 1,
  "founded": "2019-07-19",
  "naics": [
   "4711",
   "4719",
   "4721",
   "4724"
  ],
  "source": "https://arbk.org/biz/besarta-misini-bi/"
 },
 {
  "id": "811469304",
  "name": "BLERIMII",
  "legal": "BLERIMII SH.P.K.",
  "type": "market",
  "address": "Rruga Gjashtë Dëshmorët, p.n., Lubishtë",
  "phone": "+38345803454",
  "email": "blerimishpk@outlook.com",
  "employees": 1,
  "founded": "2020-10-21",
  "naics": [
   "4711",
   "4719",
   "4729"
  ],
  "source": "https://arbk.org/biz/blerimii-shpk/"
 },
 {
  "id": "811459280",
  "name": "coffee shop RONI",
  "legal": "Bled Rashiti B.I.",
  "type": "market",
  "address": "Rruga Flaka e Janarit, p.n., Viti",
  "phone": "+38344972984",
  "email": "bledrashiti2@gmail.com",
  "employees": 1,
  "founded": "2020-09-25",
  "naics": [
   "4711",
   "5610",
   "5621",
   "5630"
  ],
  "source": "https://arbk.org/biz/bled-rashiti-bi/"
 },
 {
  "id": "810675233",
  "name": "D.P.T \" Bekimi Com \"",
  "legal": "Robert Martini B.I.",
  "type": "market",
  "address": "Rruga Stubëll e Epërme, p.n., Stubëll e Epërme",
  "phone": "+38344261554",
  "email": "robertmartini431@gmail.com",
  "employees": 1,
  "founded": "2001-07-24",
  "naics": [
   "4711"
  ],
  "source": "https://arbk.org/biz/robert-martini-bi/"
 },
 {
  "id": "810671702",
  "name": "D.P.T. \" Filja \"",
  "legal": "Ramadan Zuka B.I.",
  "type": "market",
  "address": "p.n., Pozheran",
  "phone": "+38345268165",
  "email": "",
  "employees": 1,
  "founded": "2000-05-30",
  "naics": [
   "4711"
  ],
  "source": "https://arbk.org/biz/ramadan-zuka-bi/"
 },
 {
  "id": "811098450",
  "name": "D.P.T. \" GLIMI \"",
  "legal": "Përparim Nexhipi B.I.",
  "type": "market",
  "address": "p.n., Drobesh",
  "phone": "+38344424835",
  "email": "perparimnexhipi.b.i@gmail.com",
  "employees": 1,
  "founded": "2012-02-27",
  "naics": [
   "4711",
   "4719",
   "4721",
   "4729"
  ],
  "source": "https://arbk.org/biz/perparim-nexhipi-bi/"
 },
 {
  "id": "810681884",
  "name": "D.P.T. \" Labi \"",
  "legal": "Labinot Nitaj B.I.",
  "type": "market",
  "address": "Kllokot",
  "phone": "+38344102880",
  "email": "",
  "employees": 1,
  "founded": "2008-03-04",
  "naics": [
   "4711"
  ],
  "source": "https://arbk.org/biz/labinot-nitaj-bi/"
 },
 {
  "id": "811093765",
  "name": "D.P.T. \" Poli - Art \"",
  "legal": "Bashkim Hetemi B.I.",
  "type": "market",
  "address": "Rruga 2 Korriku, p.n., Viti",
  "phone": "+38344597163",
  "email": "bashk2003@gmail.com",
  "employees": 1,
  "founded": "2008-05-16",
  "naics": [
   "4711",
   "4721",
   "4724"
  ],
  "source": "https://arbk.org/biz/bashkim-hetemi-bi/"
 },
 {
  "id": "810679558",
  "name": "D.P.T. \" Rinori \"",
  "legal": "Bebush Islami B.I.",
  "type": "market",
  "address": "Remnik",
  "phone": "+38344341591",
  "email": "",
  "employees": 1,
  "founded": "2007-03-19",
  "naics": [
   "4711"
  ],
  "source": "https://arbk.org/biz/bebush-islami-bi/"
 },
 {
  "id": "810674201",
  "name": "D.P.T. \" Shkodrani - B \"",
  "legal": "Bejtush Shabiu I.B.",
  "type": "market",
  "address": "Hasan Kabashi , Viti",
  "phone": "+38344250003",
  "email": "",
  "employees": 1,
  "founded": "2000-10-10",
  "naics": [
   "4711"
  ],
  "source": "https://arbk.org/biz/bejtush-shabiu-ib/"
 },
 {
  "id": "811101154",
  "name": "D.P.T. \" SHUKI \"",
  "legal": "Shukri Pira B.I.",
  "type": "market",
  "address": "p.n., Pozheran",
  "phone": "+38344518123",
  "email": "",
  "employees": 1,
  "founded": "2013-05-07",
  "naics": [
   "4711",
   "4721",
   "4751",
   "7711"
  ],
  "source": "https://arbk.org/biz/shukri-pira-bi/"
 },
 {
  "id": "810677362",
  "name": "D.P.T. \"Loni\"",
  "legal": "Isuf Latifi B.I.",
  "type": "market",
  "address": "Ballancë",
  "phone": "+38344210958",
  "email": "",
  "employees": 1,
  "founded": "2004-02-18",
  "naics": [
   "4711"
  ],
  "source": "https://arbk.org/biz/isuf-latifi-bi/"
 },
 {
  "id": "811101146",
  "name": "D.T.P. \" MARKET TINA \"",
  "legal": "Agron E. Abazi B.I.",
  "type": "market",
  "address": "p.n., Sllatinë e Epërme",
  "phone": "+38344250346",
  "email": "",
  "employees": 1,
  "founded": "2013-05-07",
  "naics": [
   "4711",
   "4721",
   "4751"
  ],
  "source": "https://arbk.org/biz/agron-e-abazi-bi/"
 },
 {
  "id": "810681230",
  "name": "DPT ,, Florenti \"",
  "legal": "Kadrush Latifi B.I.",
  "type": "market",
  "address": "Radivojcë",
  "phone": "+38344254322",
  "email": "",
  "employees": 1,
  "founded": "2005-10-17",
  "naics": [
   "4711"
  ],
  "source": "https://arbk.org/biz/kadrush-latifi-bi/"
 },
 {
  "id": "812436831",
  "name": "Drilon Fazliu B.I.",
  "legal": "",
  "type": "market",
  "address": "KONGRESI MANASTIRIT, 75, Viti",
  "phone": "+38345344320",
  "email": "drilonfazliu10@hotmail.com",
  "employees": 1,
  "founded": "2026-07-08",
  "naics": [
   "4711",
   "4719"
  ],
  "source": "https://arbk.org/biz/drilon-fazliu-bi/"
 },
 {
  "id": "811105495",
  "name": "Enver Alidema B.I.",
  "legal": "",
  "type": "market",
  "address": "Mejdi Korrani p.n., Pozheran",
  "phone": "+38344322656",
  "email": "",
  "employees": 1,
  "founded": "2016-06-15",
  "naics": [
   "4711",
   "4719",
   "4721",
   "4724"
  ],
  "source": "https://arbk.org/biz/enver-alidema-bi/"
 },
 {
  "id": "810125197",
  "name": "Etrit Sejdiu B.I.",
  "legal": "",
  "type": "market",
  "address": "Adem Jashari p.n., Viti",
  "phone": "+38344712613",
  "email": "",
  "employees": 1,
  "founded": "2018-05-18",
  "naics": [
   "4711",
   "4725"
  ],
  "source": "https://arbk.org/biz/etrit-sejdiu-bi/"
 },
 {
  "id": "811984162",
  "name": "Faiku Palace A",
  "legal": "Faiku Palace A SH.P.K.",
  "type": "market",
  "address": "Rruga Florim Maliqi, pn, Viti",
  "phone": "+38344417273",
  "email": "aava_usa@hotmail.com",
  "employees": 1,
  "founded": "2022-11-08",
  "naics": [
   "4711",
   "4725",
   "5610",
   "5621"
  ],
  "source": "https://arbk.org/biz/faiku-palace-a-shpk/"
 },
 {
  "id": "812344191",
  "name": "Fast Food Alea",
  "legal": "Venerë Ajeti Isaku B.I.",
  "type": "market",
  "address": "AVNI RAMA, 11, Viti",
  "phone": "+38349758119",
  "email": "venera.ajeti1@hotmail.com",
  "employees": 1,
  "founded": "2025-10-28",
  "naics": [
   "4711",
   "4719",
   "4725",
   "4729"
  ],
  "source": "https://arbk.org/biz/venere-ajeti-isaku-bi/"
 },
 {
  "id": "812440519",
  "name": "FATI MARKET 2 SH.P.K.",
  "legal": "",
  "type": "market",
  "address": "QERIM RRAHMANI, 34, Vërban",
  "phone": "+38349726958",
  "email": "zariferamadani81@outlook.com",
  "employees": 1,
  "founded": "2026-07-14",
  "naics": [
   "4711",
   "4721",
   "4722",
   "4725"
  ],
  "source": "https://arbk.org/biz/fati-market-2-shpk/"
 },
 {
  "id": "811470301",
  "name": "GIJJA",
  "legal": "GIJJA SH.P.K.",
  "type": "market",
  "address": "Rruga Rexhep Sylejmani, p.n., Gërmovë",
  "phone": "+38345286236",
  "email": "gijjashpk@outlook.com",
  "employees": 1,
  "founded": "2020-10-22",
  "naics": [
   "4711",
   "4719",
   "4729"
  ],
  "source": "https://arbk.org/biz/gijja-shpk/"
 },
 {
  "id": "811984295",
  "name": "HALIM FAIKU PALACE SH.P.K.",
  "legal": "",
  "type": "market",
  "address": "Rruga Florim Maliqi, pn, Viti",
  "phone": "+38344491478",
  "email": "info@halim.at",
  "employees": 1,
  "founded": "2022-11-09",
  "naics": [
   "4711",
   "4725",
   "5610",
   "5621"
  ],
  "source": "https://arbk.org/biz/halim-faiku-palace-shpk/"
 },
 {
  "id": "811553181",
  "name": "Kioska BOSSI",
  "legal": "Selvete B. Arifi B.I.",
  "type": "market",
  "address": "Rr. Rexhep Bislimi, p.n., Viti",
  "phone": "+38344995284",
  "email": "mehmetgoshica@hotmail.com",
  "employees": 1,
  "founded": "2021-03-18",
  "naics": [
   "4711",
   "4719",
   "4722",
   "4724"
  ],
  "source": "https://arbk.org/biz/selvete-b-arifi-bi/"
 },
 {
  "id": "810022591",
  "name": "Labinot Ismajli B.I.",
  "legal": "",
  "type": "market",
  "address": "Rr. Trëstenikut p.n., Trëstenik",
  "phone": "+38344312368",
  "email": "",
  "employees": 1,
  "founded": "2017-05-03",
  "naics": [
   "4711",
   "4724"
  ],
  "source": "https://arbk.org/biz/labinot-ismajli-bi/"
 },
 {
  "id": "812329672",
  "name": "Lumi Bar",
  "legal": "Fatlum Kurteshi B.I.",
  "type": "market",
  "address": "BUDRIKA, 148, Budrikë e Epërme",
  "phone": "+38345216250",
  "email": "kurteshifatlum97@gmail.com",
  "employees": 1,
  "founded": "2025-09-16",
  "naics": [
   "4711",
   "4725",
   "5630"
  ],
  "source": "https://arbk.org/biz/fatlum-kurteshi-bi/"
 },
 {
  "id": "811401827",
  "name": "Market Buli",
  "legal": "Burim E. Haziri B.I.",
  "type": "market",
  "address": "Rr.E Verbanit, p.n, Vërban",
  "phone": "+38344397417",
  "email": "burimhaziribi@hotmail.com",
  "employees": 1,
  "founded": "2020-02-21",
  "naics": [
   "4711",
   "4719",
   "4721",
   "4725"
  ],
  "source": "https://arbk.org/biz/burim-e-haziri-bi/"
 },
 {
  "id": "812053560",
  "name": "MARKET JUSUFI",
  "legal": "Afrim Sh. Xheladini B.I.",
  "type": "market",
  "address": "Rruga Zahir Pajaziti, p.n., Drobesh",
  "phone": "+38345302914",
  "email": "afrimxheladini1@hotmail.com",
  "employees": 1,
  "founded": "2023-06-16",
  "naics": [
   "4711"
  ],
  "source": "https://arbk.org/biz/afrim-sh-xheladini-bi/"
 },
 {
  "id": "812060250",
  "name": "Market Urimi SH.P.K.",
  "legal": "",
  "type": "market",
  "address": "Rruga Hamit Ymeri, p.n., Sllatinë e Epërme",
  "phone": "+38344376664",
  "email": "market.urimi@gmail.com",
  "employees": 1,
  "founded": "2023-07-11",
  "naics": [
   "4711",
   "4721",
   "4722",
   "4724"
  ],
  "source": "https://arbk.org/biz/market-urimi-shpk/"
 },
 {
  "id": "811105859",
  "name": "Musah Fazliu B.I.",
  "legal": "",
  "type": "market",
  "address": "Safet Rexhepi p.n., Viti",
  "phone": "+38345805540",
  "email": "",
  "employees": 1,
  "founded": "2016-09-21",
  "naics": [
   "4711",
   "4721",
   "4722",
   "4724"
  ],
  "source": "https://arbk.org/biz/musah-fazliu-bi/"
 },
 {
  "id": "811093674",
  "name": "N.T.P \" Argjendi \"",
  "legal": "Gazmend I. Salihu B.I.",
  "type": "market",
  "address": "P.N., Tërpezë",
  "phone": "+38344",
  "email": "",
  "employees": 1,
  "founded": "2008-05-05",
  "naics": [
   "4711",
   "4719"
  ],
  "source": "https://arbk.org/biz/gazmend-i-salihu-bi/"
 },
 {
  "id": "811583469",
  "name": "N.T.P. \" ARDI - H \"",
  "legal": "Hysni H. Rexhepi B.I.",
  "type": "market",
  "address": "p.n., Gjylekarë",
  "phone": "+38344305123",
  "email": "",
  "employees": 1,
  "founded": "2015-06-22",
  "naics": [
   "4711",
   "4719",
   "4722"
  ],
  "source": "https://arbk.org/biz/hysni-h-rexhepi-bi/"
 },
 {
  "id": "810673857",
  "name": "N.T.P. \" BEJTA COMMERCE \"",
  "legal": "Afrim Zeneli B.I.",
  "type": "market",
  "address": "Ramnishtë, Viti, Kosovë, p.n., Ramnishtë",
  "phone": "+38344211064",
  "email": "afrimzeneli.bi@gmail.com",
  "employees": 1,
  "founded": "2000-08-14",
  "naics": [
   "4711",
   "4721"
  ],
  "source": "https://arbk.org/biz/afrim-zeneli-bi/"
 },
 {
  "id": "811420116",
  "name": "N.T.P. \" Beti \"",
  "legal": "Nikoll Gegaj B.I.",
  "type": "market",
  "address": "p.n., Binqë",
  "phone": "+38344308887",
  "email": "",
  "employees": 1,
  "founded": "2001-12-28",
  "naics": [
   "4711",
   "4719"
  ],
  "source": "https://arbk.org/biz/nikoll-gegaj-bi/"
 },
 {
  "id": "811093947",
  "name": "N.T.P. \" Blina \"",
  "legal": "Gazmend Ramadani B.I.",
  "type": "market",
  "address": "P.N., Tërpezë",
  "phone": "+38344325639",
  "email": "",
  "employees": 1,
  "founded": "2008-07-11",
  "naics": [
   "4711",
   "4721",
   "4724"
  ],
  "source": "https://arbk.org/biz/gazmend-ramadani-bi/"
 },
 {
  "id": "811103655",
  "name": "N.T.P. \" BUY MARKET \"",
  "legal": "Kushtrim Misini B.I.",
  "type": "market",
  "address": "Nikolla Teslla p.n., Viti",
  "phone": "+38348624555",
  "email": "qendrimmisini@gmail.com",
  "employees": 1,
  "founded": "2015-01-21",
  "naics": [
   "4711",
   "4721",
   "4722",
   "5621"
  ],
  "source": "https://arbk.org/biz/kushtrim-misini-bi/"
 },
 {
  "id": "811293604",
  "name": "N.T.P. \" DONA MARKET \"",
  "legal": "Sabit Ajeti B.I.",
  "type": "market",
  "address": "Preshevës p.n., Viti",
  "phone": "+38344603282",
  "email": "",
  "employees": 1,
  "founded": "2013-02-15",
  "naics": [
   "4711",
   "4719",
   "4721",
   "4724"
  ],
  "source": "https://arbk.org/biz/sabit-ajeti-bi/"
 },
 {
  "id": "811332379",
  "name": "N.T.P. \" Endrit-G.F.\"",
  "legal": "Gazmend Fazliju B.I.",
  "type": "market",
  "address": "ISA BOLETINI, 3, Viti",
  "phone": "+38344446229",
  "email": "erion.fazliu01@icloud.com",
  "employees": 1,
  "founded": "2004-02-16",
  "naics": [
   "4711",
   "4751"
  ],
  "source": "https://arbk.org/biz/gazmend-fazliju-bi/"
 },
 {
  "id": "811096892",
  "name": "N.T.P. \" LUNAD \"",
  "legal": "Xhevaire Sahiti B.I.",
  "type": "market",
  "address": "p.n., Budrikë e Epërme",
  "phone": "+38344990140",
  "email": "",
  "employees": 1,
  "founded": "2011-01-24",
  "naics": [
   "4711",
   "4721",
   "4722",
   "4724"
  ],
  "source": "https://arbk.org/biz/xhevaire-sahiti-bi/"
 },
 {
  "id": "810673873",
  "name": "N.T.P. \" Meka Com \"",
  "legal": "Esad Bilalli B.I.",
  "type": "market",
  "address": "Rr.Konjufca, p.n., Sadovinë e Çerkezve",
  "phone": "+38344210878",
  "email": "esatbilalli@gmail.com",
  "employees": 1,
  "founded": "2000-08-03",
  "naics": [
   "4711"
  ],
  "source": "https://arbk.org/biz/esad-bilalli-bi/"
 },
 {
  "id": "811099937",
  "name": "N.T.P. \" MILOŠ \"",
  "legal": "Miloš Mirkovic B.I.",
  "type": "market",
  "address": "p.n., Vrbofc",
  "phone": "+38349323168",
  "email": "",
  "employees": 1,
  "founded": "2012-12-04",
  "naics": [
   "4711",
   "4719",
   "4721",
   "4722"
  ],
  "source": "https://arbk.org/biz/milos-mirkovic-bi/"
 },
 {
  "id": "810682337",
  "name": "N.T.P. \" Tina \"",
  "legal": "Kadrushe Hajdari B.I.",
  "type": "market",
  "address": "Rruga Hasan Alia, p.n., Remnik",
  "phone": "+38344193759",
  "email": "kadrushehajdari@gmail.com",
  "employees": 1,
  "founded": "2004-07-14",
  "naics": [
   "4711"
  ],
  "source": "https://arbk.org/biz/kadrushe-hajdari-bi/"
 },
 {
  "id": "810202862",
  "name": "N.T.P. \" Uka Comerc \"",
  "legal": "Qibrie Hajdari B.I.",
  "type": "market",
  "address": "Rruga 3 Prilli, p.n., Lubishtë",
  "phone": "+38349708601",
  "email": "qibriehajdari71@gmail.com",
  "employees": 1,
  "founded": "2015-04-30",
  "naics": [
   "4711"
  ],
  "source": "https://arbk.org/biz/qibrie-hajdari-bi/"
 },
 {
  "id": "811103605",
  "name": "N.T.P. \" VERONA \"",
  "legal": "Enver Dragobuzhda B.I.",
  "type": "market",
  "address": "p.n., Pozharan",
  "phone": "+38348428349",
  "email": "enverdragobuzhda@hotmail.com",
  "employees": 1,
  "founded": "2015-01-06",
  "naics": [
   "4711",
   "4721",
   "4729"
  ],
  "source": "https://arbk.org/biz/enver-dragobuzhda-bi/"
 },
 {
  "id": "811100346",
  "name": "N.T.P. \" YLLI - YLLZA \"",
  "legal": "Bislim Doberjanca B.I.",
  "type": "market",
  "address": "p.n. , Novosellë",
  "phone": "+38344194334",
  "email": "",
  "employees": 1,
  "founded": "2013-01-24",
  "naics": [
   "4711",
   "5630"
  ],
  "source": "https://arbk.org/biz/bislim-doberjanca-bi/"
 },
 {
  "id": "810680290",
  "name": "N.T.P. \"Niveli\"",
  "legal": "Shpend Halabaku B.I.",
  "type": "market",
  "address": "Pozheran",
  "phone": "+38344322750",
  "email": "",
  "employees": 1,
  "founded": "2005-02-09",
  "naics": [
   "4711",
   "4751",
   "4771"
  ],
  "source": "https://arbk.org/biz/shpend-halabaku-bi/"
 },
 {
  "id": "811104421",
  "name": "N.T.P.'' TE ISMAJLI ''",
  "legal": "Behar Tafa B.I.",
  "type": "market",
  "address": "24 Marsi, Ramnishtë",
  "phone": "+38343834166",
  "email": "behar.tafaa@icloud.com",
  "employees": 1,
  "founded": "2015-08-05",
  "naics": [
   "4711",
   "4719",
   "4721",
   "4722"
  ],
  "source": "https://arbk.org/biz/behar-tafa-bi/"
 },
 {
  "id": "810678097",
  "name": "N.T.P.\"Artoni Comerc\"",
  "legal": "Adnan Ahmeti B.I.",
  "type": "market",
  "address": "Viti",
  "phone": "+38344250245",
  "email": "",
  "employees": 1,
  "founded": "2004-04-22",
  "naics": [
   "4711"
  ],
  "source": "https://arbk.org/biz/adnan-ahmeti-bi/"
 },
 {
  "id": "810675324",
  "name": "N.T.P.\"Buli\"",
  "legal": "Burim Rexhepi B.I.",
  "type": "market",
  "address": "p.n., Ramjan",
  "phone": "+38344274481",
  "email": "",
  "employees": 1,
  "founded": "2001-08-16",
  "naics": [
   "4711",
   "4719",
   "4724",
   "4751"
  ],
  "source": "https://arbk.org/biz/burim-rexhepi-bi/"
 },
 {
  "id": "811096610",
  "name": "N.T.SH. \" LESA \"",
  "legal": "Valbona N. Rexhepi B.I.",
  "type": "market",
  "address": "Rruga Adem Jashari, p.n., Viti",
  "phone": "+38344792020",
  "email": "valbanarexhepi@hotmail.com",
  "employees": 1,
  "founded": "2010-09-16",
  "naics": [
   "4725",
   "4726",
   "4752",
   "4775"
  ],
  "source": "https://arbk.org/biz/valbona-n-rexhepi-bi/"
 },
 {
  "id": "811101758",
  "name": "N.T.SH. \" Rinia Travel \"",
  "legal": "Fatmir H. Aliu B.I.",
  "type": "market",
  "address": "Adem Jashari p.n., Viti",
  "phone": "+38344133339",
  "email": "",
  "employees": 1,
  "founded": "2013-09-03",
  "naics": [
   "4711",
   "7911",
   "8299"
  ],
  "source": "https://arbk.org/biz/fatmir-h-aliu-bi/"
 },
 {
  "id": "810680802",
  "name": "NTP ,, Festimi \"",
  "legal": "Ruzhdi R. Ismajli B.I.",
  "type": "market",
  "address": "Sllatinë e Epërme",
  "phone": "+38344210837",
  "email": "",
  "employees": 1,
  "founded": "2005-06-21",
  "naics": [
   "4711",
   "4751",
   "4759",
   "4771"
  ],
  "source": "https://arbk.org/biz/ruzhdi-r-ismajli-bi/"
 },
 {
  "id": "811093880",
  "name": "NTP \"Euro Smira\"",
  "legal": "Samet Neziri B.I.",
  "type": "market",
  "address": "Smirë",
  "phone": "+38344341770",
  "email": "",
  "employees": 1,
  "founded": "2008-06-25",
  "naics": [
   "4711",
   "4751",
   "4754"
  ],
  "source": "https://arbk.org/biz/samet-neziri-bi/"
 },
 {
  "id": "811096909",
  "name": "P.T.P. \" VOJA PROMET \"",
  "legal": "Velibor M. Kostic B.I.",
  "type": "market",
  "address": "Gërçar",
  "phone": "+38345577932",
  "email": "",
  "employees": 1,
  "founded": "2011-01-24",
  "naics": [
   "4711",
   "4719"
  ],
  "source": "https://arbk.org/biz/velibor-m-kostic-bi/"
 },
 {
  "id": "811098301",
  "name": "P.T.P.\"LIPA \"",
  "legal": "Violeta Kojic B.I.",
  "type": "market",
  "address": "p.n., Vrbofc",
  "phone": "+38344738275",
  "email": "",
  "employees": 1,
  "founded": "2012-01-19",
  "naics": [
   "4711"
  ],
  "source": "https://arbk.org/biz/violeta-kojic-bi/"
 },
 {
  "id": "811104520",
  "name": "Ramadan Azizi B.I.",
  "legal": "",
  "type": "market",
  "address": "p.n., Budrikë e Epërme",
  "phone": "+38344446155",
  "email": "",
  "employees": 1,
  "founded": "2015-09-03",
  "naics": [
   "4781"
  ],
  "source": "https://arbk.org/biz/ramadan-azizi-bi/"
 },
 {
  "id": "811493767",
  "name": "Rioli",
  "legal": "Jetmir Abazi B.I.",
  "type": "market",
  "address": "Rruga Kemajl Azizi, p.n., Viti",
  "phone": "+38344194322",
  "email": "miliabazi1996@hotmail.com",
  "employees": 1,
  "founded": "2021-01-06",
  "naics": [
   "4711",
   "4721",
   "4724",
   "4725"
  ],
  "source": "https://arbk.org/biz/jetmir-abazi-bi/"
 },
 {
  "id": "810673617",
  "name": "Sh.P.T. \" Florimi \"",
  "legal": "Brahim Doberjanca B.I.",
  "type": "market",
  "address": "p.n., Novosellë",
  "phone": "+38344750929",
  "email": "",
  "employees": 1,
  "founded": "2000-08-17",
  "naics": [
   "4711",
   "4719"
  ],
  "source": "https://arbk.org/biz/brahim-doberjanca-bi/"
 },
 {
  "id": "810674243",
  "name": "Sh.P.T. \" Mali - Loni \"",
  "legal": "Driton Bajrami B.I.",
  "type": "market",
  "address": "p.n., Beguncë",
  "phone": "+38344211241",
  "email": "",
  "employees": 1,
  "founded": "2000-10-05",
  "naics": [
   "4711",
   "4719"
  ],
  "source": "https://arbk.org/biz/driton-bajrami-bi/"
 },
 {
  "id": "812002096",
  "name": "SHKUMBINI REISEN",
  "legal": "SHKUMBINI REISEN SH.P.K.",
  "type": "market",
  "address": "Ukë Ahmeti, p.n., Tërpezë",
  "phone": "+38344323100",
  "email": "bini_99@mns.com",
  "employees": 1,
  "founded": "2023-01-12",
  "naics": [
   "4711",
   "4721",
   "4722",
   "4724"
  ],
  "source": "https://arbk.org/biz/shkumbini-reisen-shpk/"
 },
 {
  "id": "810677396",
  "name": "T.L. Selami Nuredini",
  "legal": "Selami Nuredini B.I.",
  "type": "market",
  "address": "Rruga Amir Nuredini, p.n., Sllatinë e Epërme",
  "phone": "+38344296230",
  "email": "selaminuredini30@gmail.com",
  "employees": 1,
  "founded": "2004-02-18",
  "naics": [
   "4711",
   "4751",
   "4789",
   "9609"
  ],
  "source": "https://arbk.org/biz/selami-nuredini-bi/"
 },
 {
  "id": "812243799",
  "name": "Te Zhuti 04",
  "legal": "Përparim Bexheti B.I.",
  "type": "market",
  "address": "Rruga Budrika, Nr. 148, Budrikë e Epërme",
  "phone": "+38345780995",
  "email": "perparimbexheti04@gmail.com",
  "employees": 1,
  "founded": "2025-02-03",
  "naics": [
   "4711",
   "4725",
   "5630"
  ],
  "source": "https://arbk.org/biz/perparim-bexheti-bi/"
 },
 {
  "id": "811490854",
  "name": "TOOP",
  "legal": "TOOP SH.P.K.",
  "type": "market",
  "address": "Sadovinë e Çerkezve, pn, pn, Sadovinë e Çerkezve",
  "phone": "+38349732811",
  "email": "toopshpk@hotmail.com",
  "employees": 1,
  "founded": "2020-12-22",
  "naics": [
   "4711",
   "9311",
   "9319"
  ],
  "source": "https://arbk.org/biz/toop-shpk/"
 },
 {
  "id": "811490888",
  "name": "TOOP NBB",
  "legal": "Blend Bilalli B.I.",
  "type": "market",
  "address": "Rruga Sadovinë e Çerkezve, pn, Sadovinë e Çerkezve",
  "phone": "+38349732811",
  "email": "toop-n@hotmail.com",
  "employees": 1,
  "founded": "2020-12-22",
  "naics": [
   "4711",
   "4719",
   "4721",
   "4730"
  ],
  "source": "https://arbk.org/biz/blend-bilalli-bi/",
  "dupPhone": true
 },
 {
  "id": "811500322",
  "name": "Braha Market",
  "legal": "Florim B. Brahimi B.I.",
  "type": "market",
  "address": "Rruga Luftëtarët, pa nr, Novosellë",
  "phone": "+38344672927",
  "email": "florimbrahimi@hotmail.com",
  "employees": null,
  "founded": "2021-01-25",
  "naics": [
   "4711",
   "4799"
  ],
  "source": "https://arbk.org/biz/florim-b-brahimi-bi/"
 },
 {
  "id": "812026187",
  "name": "Candy Shop Store",
  "legal": "Candy Shop Store SH.P.K.",
  "type": "bakery",
  "address": "Rr. Flaka e Janarit, P.N., Viti",
  "phone": "+38343780432",
  "email": "candyshopviti@gmail.com",
  "employees": 1,
  "founded": "2023-03-21",
  "naics": [
   "4724",
   "4729",
   "5621",
   "5629"
  ],
  "source": "https://arbk.org/biz/candy-shop-store-shpk/"
 },
 {
  "id": "810208828",
  "name": "N.T.P. \" Pashtriku \"",
  "legal": "Jeton D. Çoçaj B.I.",
  "type": "bakery",
  "address": "Adem Jashari P.N., Viti",
  "phone": "+38344",
  "email": "",
  "employees": 1,
  "founded": "2016-02-10",
  "naics": [
   "4724"
  ],
  "source": "https://arbk.org/biz/jeton-d-cocaj-bi/",
  "dupPhone": true
 },
 {
  "id": "812074722",
  "name": "Viktoria Beg",
  "legal": "Viktoria Beg SH.P.K.",
  "type": "bakery",
  "address": "Rr. UÇK, p.n., Viti",
  "phone": "+38345781760",
  "email": "arsimavdiu8@gmail.com",
  "employees": 1,
  "founded": "2023-08-28",
  "naics": [
   "4724",
   "4729",
   "5630"
  ],
  "source": "https://arbk.org/biz/viktoria-beg-shpk/"
 },
 {
  "id": "811341734",
  "name": "N LIBURN",
  "legal": "Drilon Sadriu B.I.",
  "type": "cafe",
  "address": "Adem Jashari, p.n., Viti",
  "phone": "+38349730732",
  "email": "drilonsadriu@hotmail.com",
  "employees": 3,
  "founded": "2019-08-16",
  "naics": [
   "5630"
  ],
  "source": "https://arbk.org/biz/drilon-sadriu-bi/"
 },
 {
  "id": "812262749",
  "name": "LIO BAR",
  "legal": "Fatmir Zefi B.I.",
  "type": "cafe",
  "address": "Adem Jashari, p.n., Viti",
  "phone": "+38344923694",
  "email": "mirlindaa8.zefii8@gmail.com",
  "employees": 2,
  "founded": "2025-03-26",
  "naics": [
   "5630"
  ],
  "source": "https://arbk.org/biz/fatmir-zefi-bi/"
 },
 {
  "id": "812299073",
  "name": "MOOBAR17",
  "legal": "Xhevahir Rrahmani B.I.",
  "type": "cafe",
  "address": "Rr. Adem Jashari, p.n., Viti",
  "phone": "+38349712044",
  "email": "17moobar17@gmail.com",
  "employees": 2,
  "founded": "2025-06-30",
  "naics": [
   "5630"
  ],
  "source": "https://arbk.org/biz/xhevahir-rrahmani-bi/"
 },
 {
  "id": "811330050",
  "name": "N TE 8 TSH",
  "legal": "Adnan Se. Sylejmani B.I.",
  "type": "cafe",
  "address": "2 korrigu, p.n., Viti",
  "phone": "+38345201210",
  "email": "adnani_gv@hotmail.com",
  "employees": 2,
  "founded": "2019-07-10",
  "naics": [
   "5630",
   "6190",
   "9312"
  ],
  "source": "https://arbk.org/biz/adnan-se-sylejmani-bi/"
 },
 {
  "id": "812260339",
  "name": "ZONE GAMING CAFFE SH.P.K.",
  "legal": "",
  "type": "cafe",
  "address": "Rruga UÇK, p.n., Viti",
  "phone": "+38345430915",
  "email": "xhelilbilalli2001@gmail.com",
  "employees": 2,
  "founded": "2025-03-20",
  "naics": [
   "5630",
   "6209",
   "9329"
  ],
  "source": "https://arbk.org/biz/zone-gaming-caffe-shpk/"
 },
 {
  "id": "811330084",
  "name": "Adem Z. Tahiri B.I.",
  "legal": "",
  "type": "cafe",
  "address": "Gjemail Ademi, p.n., Viti",
  "phone": "+38345339400",
  "email": "ademtahiri10@gmail.com",
  "employees": 1,
  "founded": "2019-07-10",
  "naics": [
   "5630",
   "6190"
  ],
  "source": "https://arbk.org/biz/adem-z-tahiri-bi/"
 },
 {
  "id": "811880344",
  "name": "Blackmoon",
  "legal": "Blackmoon SH.P.K.",
  "type": "cafe",
  "address": "Rruga Adem Jashari, p.n, Viti",
  "phone": "+38348888191",
  "email": "sefisefija@gmail.com",
  "employees": 1,
  "founded": "2021-11-25",
  "naics": [
   "5630"
  ],
  "source": "https://arbk.org/biz/blackmoon-shpk/"
 },
 {
  "id": "811106146",
  "name": "Bojan Cvetković I.B.",
  "legal": "Bojan D. Cvetkovic I.B.",
  "type": "cafe",
  "address": "p.n., Kllokot",
  "phone": "+38344642595",
  "email": "",
  "employees": 1,
  "founded": "2016-12-28",
  "naics": [
   "5630"
  ],
  "source": "https://arbk.org/biz/bojan-d-cvetkovic-ib/"
 },
 {
  "id": "811580449",
  "name": "CAFFE BAR TE RRETHI",
  "legal": "CAFFE BAR TE RRETHI SH.P.K.",
  "type": "cafe",
  "address": "Rruga Hoxhë Jonuzi, p.n, Viti",
  "phone": "+38344673388",
  "email": "almasi5@hotmail.com",
  "employees": 1,
  "founded": "2021-06-11",
  "naics": [
   "5630"
  ],
  "source": "https://arbk.org/biz/caffe-bar-te-rrethi-shpk/"
 },
 {
  "id": "811894288",
  "name": "CAFFE PINOCCHIO",
  "legal": "CAFFE PINOCCHIO SH.P.K.",
  "type": "cafe",
  "address": "Magjistralja Viti-Ferizaj, p.n, Sadovinë e Jerlive",
  "phone": "+38344669881",
  "email": "artonferizi@hotmail.com",
  "employees": 1,
  "founded": "2022-01-18",
  "naics": [
   "5630"
  ],
  "source": "https://arbk.org/biz/caffe-pinocchio-shpk/"
 },
 {
  "id": "812401983",
  "name": "CaffeBar Dioni SH.P.K.",
  "legal": "",
  "type": "cafe",
  "address": "KONGRESI MANASTIRIT, 34, Viti",
  "phone": "+38343857648",
  "email": "albini.ademii1@autlook.com",
  "employees": 1,
  "founded": "2026-04-03",
  "naics": [
   "5630"
  ],
  "source": "https://arbk.org/biz/caffebar-dioni-shpk/"
 },
 {
  "id": "811913385",
  "name": "CITY BAR",
  "legal": "CITY BAR SH.P.K.",
  "type": "cafe",
  "address": "Rruga Adem Jashari, p.n, Viti",
  "phone": "+38348232023",
  "email": "citybarshpk@gmail.com",
  "employees": 1,
  "founded": "2022-03-18",
  "naics": [
   "5630"
  ],
  "source": "https://arbk.org/biz/city-bar-shpk/"
 },
 {
  "id": "811100627",
  "name": "D.P.H. \" BIZARRO BAR 1 \"",
  "legal": "Lavdim M. Rama B.I.",
  "type": "cafe",
  "address": "p.n., Pozheran",
  "phone": "+38344146108",
  "email": "",
  "employees": 1,
  "founded": "2013-02-12",
  "naics": [
   "5630"
  ],
  "source": "https://arbk.org/biz/lavdim-m-rama-bi/"
 },
 {
  "id": "811541904",
  "name": "D.P.H.\"Bling\"",
  "legal": "Argjend Arifi B.I.",
  "type": "cafe",
  "address": "Adem Jashari p.n., Viti",
  "phone": "+38345532468",
  "email": "",
  "employees": 1,
  "founded": "2013-03-12",
  "naics": [
   "5630"
  ],
  "source": "https://arbk.org/biz/argjend-arifi-bi/"
 },
 {
  "id": "811195876",
  "name": "D.P.T. '' CAPONE \"",
  "legal": "Faruk Imeri B.I.",
  "type": "cafe",
  "address": "Adem Jashari p.n., Viti",
  "phone": "+38344396879",
  "email": "",
  "employees": 1,
  "founded": "2010-08-04",
  "naics": [
   "5630"
  ],
  "source": "https://arbk.org/biz/faruk-imeri-bi/"
 },
 {
  "id": "811428756",
  "name": "Gym plus",
  "legal": "Lulzim Shabiu B.I.",
  "type": "cafe",
  "address": "Rruga Flaka e Janarit, p.n., Viti",
  "phone": "+38345945012",
  "email": "lulzimshabiu@hotmail.com",
  "employees": 1,
  "founded": "2020-06-16",
  "naics": [
   "5630",
   "9319",
   "9329",
   "9604"
  ],
  "source": "https://arbk.org/biz/lulzim-shabiu-bi/"
 },
 {
  "id": "812453231",
  "name": "Hi Five Bar SH.P.K.",
  "legal": "",
  "type": "cafe",
  "address": "ADEM JASHARI, 66, Viti",
  "phone": "+38344269287",
  "email": "rizaahmeti2026@outlook.com",
  "employees": 1,
  "founded": "2026-08-11",
  "naics": [
   "5630"
  ],
  "source": "https://arbk.org/biz/hi-five-bar-shpk/"
 },
 {
  "id": "811368481",
  "name": "Kolos Bar",
  "legal": "Kolos Bar SH.P.K.",
  "type": "cafe",
  "address": "adem jashari, p.n., Viti",
  "phone": "+38349888243",
  "email": "shkumbin.sylejmani@gmail.com",
  "employees": 1,
  "founded": "2019-11-04",
  "naics": [
   "5630"
  ],
  "source": "https://arbk.org/biz/kolos-bar-shpk/"
 },
 {
  "id": "811577389",
  "name": "N'ZA CAFFE",
  "legal": "N’ZA CAFFE SH.P.K.",
  "type": "cafe",
  "address": "Rruga Adem Jashari, P.n., Viti",
  "phone": "+38349770696",
  "email": "festim_2@hotmail.com",
  "employees": 1,
  "founded": "2021-06-03",
  "naics": [
   "5630"
  ],
  "source": "https://arbk.org/biz/nza-caffe-shpk/"
 },
 {
  "id": "812288422",
  "name": "otto bar SH.P.K.",
  "legal": "",
  "type": "cafe",
  "address": "Adem Jashari, P.N., Viti",
  "phone": "+38344915886",
  "email": "shkumbinhaliti2004@outlook.com",
  "employees": 1,
  "founded": "2025-05-30",
  "naics": [
   "5630"
  ],
  "source": "https://arbk.org/biz/otto-bar-shpk/"
 },
 {
  "id": "810005654",
  "name": "Pranvera Halimi B.I.",
  "legal": "",
  "type": "cafe",
  "address": "Mejdi Korrani p.n., Pozheran",
  "phone": "+38345629896",
  "email": "",
  "employees": 1,
  "founded": "2017-03-14",
  "naics": [
   "5630"
  ],
  "source": "https://arbk.org/biz/pranvera-halimi-bi/"
 },
 {
  "id": "811365990",
  "name": "TIMES LOUNGE BAR",
  "legal": "TIMES LOUNGE BAR SH.P.K.",
  "type": "cafe",
  "address": "Adem Jashari, p.n., Viti",
  "phone": "+38344194244",
  "email": "durimsahiti@hotmail.com",
  "employees": 1,
  "founded": "2019-10-29",
  "naics": [
   "5630"
  ],
  "source": "https://arbk.org/biz/times-lounge-bar-shpk/"
 },
 {
  "id": "811402651",
  "name": "TOGO BAR",
  "legal": "TOGO BAR SH.P.K.",
  "type": "cafe",
  "address": "Adem Jashari, p.n., Viti",
  "phone": "+38344655549",
  "email": "togobar@outlook.com",
  "employees": 1,
  "founded": "2020-02-24",
  "naics": [
   "5630"
  ],
  "source": "https://arbk.org/biz/togo-bar-shpk/"
 },
 {
  "id": "812199512",
  "name": "XETI GAMING CENTER SH.P.K.",
  "legal": "",
  "type": "cafe",
  "address": "Adem Jashari, p.n, Viti",
  "phone": "+38343514775",
  "email": "xetigamingcenter@outlook.com",
  "employees": 1,
  "founded": "2024-09-18",
  "naics": [
   "5630",
   "6110",
   "6190",
   "6209"
  ],
  "source": "https://arbk.org/biz/xeti-gaming-center-shpk/"
 }
];
